### ISSUE TITLE
Milestone 3: Finish the user page

### ISSUE THREAD

**Issue by adb1042** [Intro-to-SE-lab-Spring-22/Group-8#21]
- [x] remove Spyke_WIP.png from the User Page
- [ ] Write the HTML for the User Page 
- [ ] Write the CSS for the User Page, background should match the Front Page of the website.
